name: Tự Động Săn Link Bóng Đá Hằng Ngày

on:
  schedule:
    - cron: '30 11 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Kéo mã nguồn về máy chủ
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0

    - name: Cài đặt Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cài đặt vũ khí Playwright và Stealth
      run: |
        pip install playwright playwright-stealth
        playwright install chromium

    - name: Kích hoạt Siêu Bot đi săn link
      env:
        PROXY_IP: ${{ secrets.PROXY_IP }}
        PROXY_PORT: ${{ secrets.PROXY_PORT }}
        PROXY_USER: ${{ secrets.PROXY_USER }}
        PROXY_PASS: ${{ secrets.PROXY_PASS }}
      run: python san_link_bong_da.py

    - name: Đẩy file m3u mới lên kho chứa công khai
      run: |
        git config --global user.name "actions-user"
        git config --global user.email "actions@github.com"
        git add tong_hop_bong_da.m3u
        git commit -m "Cập nhật luồng trực tiếp mới nhất" || echo "Không có thay đổi"
        git pull --rebase origin main
        git push origin main
